adding:
  url_http: 'http://matomo.zodiaczingers.ddev.site/'
  url_https: 'https://matomo.zodiaczingers.ddev.site/'
removing:
  url_http: 'http://matomo.zodiaczingers.com/'
  url_https: 'https://matomo.zodiaczingers.com/'
